module.exports = {
    mustDeps: [
        {block: 'root'},
        {block: 'reboot'},
    ],
    shouldDeps: [
        {block: 'type'},
        {block: 'alert'},
        {block: 'badge'},
        {block: 'breadcrumb'},
        {block: 'button-group'},
        {block: 'buttons'},
        {block: 'card'},
        {block: 'carousel'},
        {block: 'close'},
        {block: 'code'},
        {block: 'custom-forms'},
        {block: 'dropdown'},
        {block: 'forms'},
        {block: 'grid'},
        {block: 'images'},
        {block: 'input-group'},
        {block: 'jumbotron'},
        {block: 'list-group'},
        {block: 'media'},
        {block: 'modal'},
        {block: 'nav'},
        {block: 'navbar'},
        {block: 'pagination'},
        {block: 'popover'},
        {block: 'progress'},
        {block: 'tables'},
        {block: 'tooltip'},
        {block: 'transitions'},
        {block: 'utilities'},
        {block: 'print'},
    ],
};
